---
- name: create ceph config dir
  file:
    path: "{{ inventory_dir }}/{{ kube_cluster_name }}-ceph"
    state: directory
  delegate_to: localhost
  connection: local
  run_once: true

- name: generate ceph.conf
  template: src=ceph/ceph.conf.tmpl dest={{ inventory_dir }}/{{ kube_cluster_name }}-ceph/ceph.conf
  delegate_to: localhost
  connection: local
  run_once: true

- name: generate admin.keyring
  template: src=ceph/admin.keyring.tmpl dest={{ inventory_dir }}/{{ kube_cluster_name }}-ceph/admin.keyring
  delegate_to: localhost
  connection: local
  run_once: true

- name: generate admin.keyring
  template: src=ceph/mon.keyring.tmpl dest={{ inventory_dir }}/{{ kube_cluster_name }}-ceph/mon.keyring
  delegate_to: localhost
  connection: local
  run_once: true

- name: generate bootstrap.keyring
  template: src=ceph/bootstrap.keyring.tmpl dest={{ inventory_dir }}/{{ kube_cluster_name }}-ceph/bootstrap-{{ item }}.keyring
  delegate_to: localhost
  connection: local
  run_once: true
  with_items:
      - osd
      - mds
      - rgw

- name: slurp bootstrap keyrings
  slurp:
      src: "{{ inventory_dir }}/{{ kube_cluster_name }}-ceph/bootstrap-{{ item }}.keyring"
  delegate_to: localhost
  connection: local
  run_once: true
  with_items:
      - osd
      - mds
      - rgw
  register: bootstrap_secrets

- name: debut bootstrap_secrets
  run_once: true
  debug:
      var: bootstrap_secrets


- name: template bootstrap keyring secrets
  template: 
      src: kubernetes/ceph-bootstrap-secret.tmpl
      dest: '{{ inventory_dir}}/{{ kube_cluster_name }}-ceph/bootstrap-{{ item.item }}.yml'
  register: bootstrap
  delegate_to: localhost
  connection: local
  run_once: true
  with_items: '{{ bootstrap_secrets.results }}'

- name: slurp ceph.conf
  slurp:
      src: "{{ inventory_dir }}/{{ kube_cluster_name }}-ceph/ceph.conf"
  register: ceph_conf
  delegate_to: localhost
  connection: local
  run_once: true

- name: slurp ceph.conf
  slurp:
      src: "{{ inventory_dir }}/{{ kube_cluster_name }}-ceph/admin.keyring"
  register: ceph_admin_keyring
  delegate_to: localhost
  connection: local
  run_once: true

- name: slurp ceph.conf
  slurp:
      src: "{{ inventory_dir }}/{{ kube_cluster_name }}-ceph/mon.keyring"
  register: ceph_mon_keyring
  delegate_to: localhost
  connection: local
  run_once: true

- set_fact:
    name: ceph-conf-combined
    ceph_conf_val: "{{ ceph_conf.content }}"
    ceph_admin_keyring_val: "{{ ceph_admin_keyring.content }}"
    ceph_mon_keyring_val: "{{  ceph_mon_keyring.content }}"
  run_once: true

- name: debug
  debug:
    var: ceph_conf_val
  run_once: true
- name: debug
  debug:
    var: ceph_admin_keyring_val
  run_once: true
- name: debug
  debug:
    var: ceph_mon_keyring_val
  run_once: true


- name: template ceph-conf-combined.yml
  template:
      src: kubernetes/ceph-conf-combined.tmpl
      dest: "{{ inventory_dir }}/{{ kube_cluster_name }}-ceph/combined.yaml"
  delegate_to: localhost
  connection: local
  run_once: true

- name: templtae k8s resources
  template: 
      src: kubernetes/{{ item }}
      dest: "{{ inventory_dir }}/{{ kube_cluster_name }}-ceph/{{ item  }}"
  delegate_to: localhost
  connection: local
  run_once: true
  with_items:
      - ceph-mon-check-v1-rc.yaml
      - ceph-mon-v1-ds.yaml
      - ceph-mon-v1-svc.yaml
      - ceph-namespace.yaml
      - ceph-osd-v1-ds.yaml
      - ceph-mds-v1-dp.yaml

